# Changes here will be overwritten by Copier
_commit: v0.3.0
_src_path: gh:meltano/edk
admin_name: Henning Holgersen
cli_prefix: radlineage
extension_description: A meltano utility extension for RadLineage that wraps the `meltano-lineage`
    command.
extension_id: radlineage-ext
extension_name: RadLineage
extension_name_lower: radlineage
library_name: radlineage_ext
wrapper_target_name: meltano-lineage
